### ISSUE TITLE
Sign up for the editing service

### ISSUE THREAD

**Issue by kris-nova** [heptio/thekubelets#2]
@carlisia can you add the link to the service

@kris-nova can you sign up please

**Comment by carlisia** [comment]
Website: [https://www.weeditpodcasts.com/pricing/](https://www.weeditpodcasts.com/pricing/)

Service offers: editing, full ID3 tagging and artwork upload, transcript AND show notes, w/ intro’s and outro’s messages.

Be sure to sign up to a package that gives us transcripts and show notes as well.

Sample pricing structure:
5 episodes/month: $649
4 episodes/month: $543

**Comment by carlisia** [comment]
Done
