### ISSUE TITLE
012 - Distributed Systems without a Degree

### ISSUE THREAD

**Issue by embano1** [heptio/thekubelets#39]
Background: not everyone has a formal education/degree on distributed systems. How do you get started if you're not an expert on the matter? We'll talk about books, history and other (online) resources to get everyone excited - no matter which background you have.

**Comment by carlisia** [comment]
https://hackmd.io/FmdyltS4TwaRZJ84VX4UqA?both

**Comment by carlisia** [comment]
Done.

**Comment by carlisia** [comment]
Done.
