### ISSUE TITLE
Setup publishing + hosting

### ISSUE THREAD

**Issue by kris-nova** [heptio/thekubelets#8]
Soundcloud, iTunes, pod network, etc

**Comment by carlisia** [comment]
Examples:
![image](https://user-images.githubusercontent.com/16508/47237907-466df800-d395-11e8-83d1-4321225c4ba5.png)

**Comment by carlisia** [comment]
Service for distribution: https://www.libsyn.com/

**Comment by carlisia** [comment]
+ Spotify

**Comment by petermbenjamin** [comment]
Anchor (which was acquired by Spotify) allows you to create, distribute, and host unlimited episodes and shows for free - https://anchor.fm

There is also an open-source project for podcast hosting (sponsored by Software Engineering Daily, I believe) - https://github.com/crablar/podsheets

**Comment by carlisia** [comment]
Super appreciated @petermbenjamin! 👍

**Comment by carlisia** [comment]
Done.
